apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-13
  name: ex-13
spec:
  containers:
  - image: nginx
    name: ex-13
    ports:
    - containerPort: 80
    resources: {}
    env:
    - name: tier
      value: "web"
    - name: enrironment
      value: "dev"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
