apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-1
  name: ex-1
spec:
  containers:
  - image: nginx
    name: ex-1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
