apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-1
  name: deploy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
