apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-14
  name: ex-14
spec:
  containers:
  - image: busybox
    name: ex-14
    ports:
    - containerPort: 80
    resources: {}
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 3600;done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
