apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-30
  name: deploy-30
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-30
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-30
    spec:
      containers:
      - image: nginx
        name: web
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: tier
          value: "web"
        - name: enrironment
          value: "prod"
      - image: busybox
        name: sleep
        resources: {}
        command: [ "sleep" ]
        args: [ "30" ]
status: {}
